export const GET_USER = "GET_USER";
export const SELECT_CUSTOMER = "SELECT_CUSTOMER";
export const SELECT_PRODUCT = "SELECT_PRODUCT";
export const QUANTITY_PRODUCTS = "QUANTITY_PRODUCTS";
export const UPDATE_TOTALPAYABLE = "UPDATE_TOTALPAYABLE";
export const CLEAN_GLOBAL_STATE = "CLEAN_GLOBAL_STATE";
